# Generated by Django 5.2.7 on 2025-11-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_studentcourseenrollment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcourseenrollment',
            unique_together={('student', 'course')},
        ),
    ]
